version: "3.8"

services:
  lambda:
    build: ./Lambda/llm_lambda_test
    container_name: brain-lambda
    ports:
      - "9000:8080"
    volumes:
      - ~/.aws:/root/.aws:ro   
    environment:
      AWS_DEFAULT_REGION: ap-south-1
      DOCUMENTS_S3_BUCKET: chatbot-document-v2-config
      TEMP_DATA_KEY: project_data/uploads/temp
      DOCUMENTS_DATA_KEY: project_data/uploads/documents
      METADATA_TABLE: document-metadata
      CHAT_HISTORY_TABLE: chat-history
      CONFIG_BUCKET: chatbot-document-v2-config
      CONFIG_KEY: config/config.yaml
      VECTOR_DB_HOST: 28b2ee72-9fc9-4ecd-acdf-d024c1c7bf5d.eu-west-1-0.aws.cloud.qdrant.io
      VECTOR_DB_PORT: 6333
      VECTOR_DB_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.U6PprcKnZl1ByQCBOurGp-ObPUmn0hKaUeZtenYEQ_8
      COLLECTION_NAME: Demo
      VECTOR_DIMENSION: 1024

  ui:
    build: ./ui            
    container_name: brain-ui
    ports:
      - "3000:80"
    depends_on:
      - lambda
