faiss_db:
  collection_name: "document_portal"

embedding_models:
  openai:
    provider: "openai"
    model_name: "text-embedding-3-small"
    import_path: "langchain_openai.OpenAIEmbeddings"
    secret_name: "openai/api_key"   # Hardcoded secret name in config

retriever:
  top_k: 10

llms:
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0.2
    max_output_tokens: 2048
    import_path: "langchain_openai.ChatOpenAI"
    secret_name: "openai/api_key"   