name: Deploy UI to S3

on:
  push:
    branches:
      - feature/ui   # adjust to your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies & build UI
        working-directory: ./ui
        run: |
          npm install
          npm run build

      - name: Sync UI build to S3
        run: |
          aws s3 sync ui/build/ s3://${{ secrets.UI_BUCKET_NAME }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2   # adjust region
